{
    'name': 'OTIF 100',
    'description': 'Production control system to achieve 100% On Time In Full delivery',
    'author': 'Matias Birrell R.',
    'website': 'https://www.goldfishltd.cl',
    'category': 'PRO',
    'version': '2.0.0',
    'depends': [
        'base',
        'mail',
    ],
    'data': [  # Todos los archivos CSV y XML que va a detectar el sistema
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/partner.xml',
        'views/otif100.xml',
        'views/work_order.xml',
        'views/family.xml',
        'views/sku.xml',
        'views/nonworkingdays.xml',
        'views/plant.xml',
        'views/help.xml',
        'data/actionscheduler.xml',
        'wizard/color_update.xml',
    ],
    'application': True,
}
